const express = require('express') 
const authRouters = require('./server/auth/auth.route') 
const userRoutes = require('./server/user/user.route') 
const thesisRoutes = require('./server/thesis/thesis.route') 
const preSelRoutes = require('./server/routes/presel.route') 
const thesisApplyRoutes = require('./server/routes/thesisapply.route')
const logsRoutes = require('./server/routes/logs.route') 
const dashboardRoutes = require('./server/routes/dashboard.route') 
const profileRoutes = require('./server/routes/profile.route')
const thesisCheckRoutes = require('./server/routes/thesischeck.route') 
const teacherRoutes = require('./server/routes/mentor.route') 
const messageRoutes = require('./server/routes/message.route') 
const router = express.Router()
router.get('/help-check',(req,res) => {
	res.send('OK')
})
router.use('/users/', userRoutes)
router.use('/student/', userRoutes)
router.use('/thesis/', thesisRoutes)
router.use('/preselection/',preSelRoutes)
router.use('/thesisapply/',thesisApplyRoutes)
router.use('/logs/',logsRoutes)
router.use('/dashboard/',dashboardRoutes)
router.use('/profile/',profileRoutes)
router.use('/thesischeck/',thesisCheckRoutes)
router.use('/teacher/',teacherRoutes)
router.use('/message/',messageRoutes)
module.exports = router